import { Member } from '../../src/collective'

export const backers: Member[] = [
  {
    MemberId: 8198,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'kazz',
    github: 'https://github.com/kazup01',
  },
  {
    MemberId: 8764,
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Freegames66',
    github: null,
  },
  {
    MemberId: 1770,
    type: 'ORGANIZATION',
    role: 'HOST',
    isActive: true,
    name: 'Open Source Collective 501c6 (Non Profit)',
    github: null,
  },
  {
    MemberId: 1905,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Mukesh Soni',
    github: null,
  },
  {
    MemberId: 1908,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Darko Kukovec',
    github: null,
  },
  {
    MemberId: 1892,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Luke Page',
    github: null,
  },
  {
    MemberId: 1950,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Emmanuel Vuigner',
    github: null,
  },
  {
    MemberId: 1909,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Kostas Manionis',
    github: null,
  },
  {
    MemberId: 1881,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Evan Jacobs',
    github: 'https://github.com/probablyup',
  },
  {
    MemberId: 1910,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Simon Kjellberg',
    github: null,
  },
  {
    MemberId: 1902,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Kevin James',
    github: null,
  },
  {
    MemberId: 1924,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Rafał Filipek',
    github: 'https://github.com/RafalFilipek',
  },
  {
    MemberId: 1948,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Joel Chen',
    github: null,
  },
  {
    MemberId: 1879,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Web Desserts',
    github: 'https://github.com/webdesserts',
  },
  {
    MemberId: 1894,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Matt lewis',
    github: null,
  },
  {
    MemberId: 1959,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Gil Barbara',
    github: 'https://github.com/gilbarbara',
  },
  {
    MemberId: 1878,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Andrey Popp',
    github: null,
  },
  {
    MemberId: 1876,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Sean Clayton',
    github: null,
  },
  {
    MemberId: 1922,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'spalger',
    github: null,
  },
  {
    MemberId: 1899,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Parker Bond',
    github: null,
  },
  {
    MemberId: 1920,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Kent C. Dodds',
    github: 'https://github.com/kentcdodds',
  },
  {
    MemberId: 2297,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Patrick Neschkudla',
    github: null,
  },
  {
    MemberId: 2266,
    type: 'USER',
    role: 'BACKER',
    isActive: true,
    name: 'Moritz Mahringer',
    github: null,
  },
  {
    MemberId: 2274,
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Frontend Masters',
    github: null,
  },
  {
    MemberId: 2258,
    type: 'ORGANIZATION',
    role: 'BACKER',
    isActive: true,
    name: 'Tipe',
    github: null,
  },
  {
    MemberId: 2293,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'david8',
    github: null,
  },
  {
    MemberId: 2299,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Jan-Kanty Pawelski',
    github: null,
  },
  {
    MemberId: 2354,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Botika',
    github: 'https://github.com/botika',
  },
  {
    MemberId: 2245,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Michael Lebas',
    github: null,
  },
  {
    MemberId: 2424,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Ari Palo',
    github: null,
  },
  {
    MemberId: 2461,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Dana Woodman',
    github: null,
  },
  {
    MemberId: 2365,
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Sebastian Software GmbH',
    github: null,
  },
  {
    MemberId: 2444,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Endel Dreyer',
    github: null,
  },
  {
    MemberId: 2430,
    type: 'USER',
    role: 'BACKER',
    isActive: true,
    name: 'Perry Poon',
    github: null,
  },
  {
    MemberId: 2460,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Jurica Železnjak',
    github: null,
  },
  {
    MemberId: 2588,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Alejandro Brozzo',
    github: null,
  },
  {
    MemberId: 2587,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Ajit Singh',
    github: null,
  },
  {
    MemberId: 2496,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Yanagi Motonari',
    github: null,
  },
  {
    MemberId: 2561,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Leonidas Esteban',
    github: null,
  },
  {
    MemberId: 2498,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Arjun Sarode',
    github: null,
  },
  {
    MemberId: 2491,
    type: 'ORGANIZATION',
    role: 'BACKER',
    isActive: true,
    name: 'Capital One',
    github: null,
  },
  {
    MemberId: 2518,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Karan Nijhawan',
    github: null,
  },
  {
    MemberId: 2546,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Sean Matheson',
    github: null,
  },
  {
    MemberId: 2564,
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'ZEIT',
    github: null,
  },
  {
    MemberId: 2556,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Sijie Tian',
    github: null,
  },
  {
    MemberId: 2489,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Suhas Deshpande',
    github: null,
  },
  {
    MemberId: 2558,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Sergio Xalambrí',
    github: null,
  },
  {
    MemberId: 2517,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Jared Palmer',
    github: null,
  },
  {
    MemberId: 2562,
    type: 'USER',
    role: 'BACKER',
    isActive: true,
    name: 'Dano Alexander',
    github: null,
  },
  {
    MemberId: 2510,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Harun Hasdal',
    github: null,
  },
  {
    MemberId: 2509,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Gaël Marziou',
    github: null,
  },
  {
    MemberId: 2513,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Darren Scerri',
    github: null,
  },
  {
    MemberId: 2617,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: false,
    name: 'Craig Nguyen',
    github: null,
  },
  {
    MemberId: 2662,
    type: 'USER',
    role: 'BACKER',
    tier: 'Backer',
    isActive: true,
    name: 'Jonathan Kim',
    github: null,
  },
  {
    MemberId: 7691,
    type: 'ORGANIZATION',
    role: 'BACKER',
    isActive: true,
    name: 'Airbnb',
    github: 'https://github.com/airbnb',
  },
  {
    MemberId: 19139,
    type: 'ORGANIZATION',
    role: 'BACKER',
    tier: 'Sponsor',
    isActive: false,
    name: 'Airbnb',
    github: 'https://github.com/airbnb',
  },
]
