export default {
  action: 'added',
  installation: {
    id: 1249170,
    account: {
      login: 'znarf',
      id: 806,
      node_id: 'MDQ6VXNlcjgwNg==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/806?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/znarf',
      html_url: 'https://github.com/znarf',
      followers_url: 'https://api.github.com/users/znarf/followers',
      following_url:
        'https://api.github.com/users/znarf/following{/other_user}',
      gists_url: 'https://api.github.com/users/znarf/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/znarf/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/znarf/subscriptions',
      organizations_url: 'https://api.github.com/users/znarf/orgs',
      repos_url: 'https://api.github.com/users/znarf/repos',
      events_url: 'https://api.github.com/users/znarf/events{/privacy}',
      received_events_url: 'https://api.github.com/users/znarf/received_events',
      type: 'User',
      site_admin: false,
    },
    repository_selection: 'selected',
    access_tokens_url:
      'https://api.github.com/app/installations/1249170/access_tokens',
    repositories_url: 'https://api.github.com/installation/repositories',
    html_url: 'https://github.com/settings/installations/1249170',
    app_id: 29949,
    target_id: 806,
    target_type: 'User',
    permissions: {
      contents: 'write',
      issues: 'write',
      pull_requests: 'write',
      metadata: 'read',
    },
    events: ['issues', 'pull_request'],
    created_at: 1562685075,
    updated_at: 1562685075,
    single_file_name: null,
  },
  repository_selection: 'selected',
  repositories_added: [
    {
      id: 196021640,
      node_id: 'MDEwOlJlcG9zaXRvcnkxOTYwMjE2NDA=',
      name: 'backyourstack',
      full_name: 'znarf/backyourstack',
      private: false,
    },
    {
      id: 196021641,
      node_id: 'MDEwOlJlcG9zaXRvcnkxOTYwMjE2NDB=',
      name: 'amateur',
      full_name: 'znarf/amateur',
      private: false,
    },
  ],
  repositories_removed: [],
  sender: {
    login: 'znarf',
    id: 806,
    node_id: 'MDQ6VXNlcjgwNg==',
    avatar_url: 'https://avatars3.githubusercontent.com/u/806?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/znarf',
    html_url: 'https://github.com/znarf',
    followers_url: 'https://api.github.com/users/znarf/followers',
    following_url: 'https://api.github.com/users/znarf/following{/other_user}',
    gists_url: 'https://api.github.com/users/znarf/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/znarf/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/znarf/subscriptions',
    organizations_url: 'https://api.github.com/users/znarf/orgs',
    repos_url: 'https://api.github.com/users/znarf/repos',
    events_url: 'https://api.github.com/users/znarf/events{/privacy}',
    received_events_url: 'https://api.github.com/users/znarf/received_events',
    type: 'User',
    site_admin: false,
  },
}
